### ISSUE TITLE
Integrate an automated spell checking command using cspell

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal-template#117]
https://cspell.org/

**Comment by joshsedl** [comment]
Also activate https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker which uses cspell internally

**Comment by joshsedl** [comment]
CSpell is used for Drupal core issues, which would be another reason to have this as both a linter and a custom ddrv command

**Comment by JPustkuchen** [comment]
Just came across the same! :)
Good point! Do it :)

**Comment by joshsedl** [comment]
Done through https://github.com/webksde/ddev-vscode-devcontainer-drupal-template/commit/57aa3041d8ddb074be77d74f02208b19fb004d19
