### ISSUE TITLE
Implement Git Convention Linter (Conventional Commits)

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal-template#120]
Find the best way to enforce the usage of conventional commits!

A possibility might be using [Husky](https://typicode.github.io/husky/#/?id=manual) to hook into git and apply the [Commit Lint](https://github.com/conventional-changelog/commitlint). But there are further tools which make more sense here. Checkout https://www.conventionalcommits.org/en/about/ and find the right tool for this. 

(https://github.com/conventional-commits/php-commitizen might also be a good approach)

**Comment by JPustkuchen** [comment]
We shouldn't force this, better opt into, I think. What's @thomasfrobieter's oppinion?

Still I like the style, but not the right place and project for such heavy enforcements, I think.
