### ISSUE TITLE
Provide SCSS & CSS formatters (Prettier)

### ISSUE THREAD

**Issue by thomasfrobieter** [webksde/ddev-vscode-devcontainer-drupal-template#149]
![grafik](https://github.com/webksde/ddev-vscode-devcontainer-drupal-template/assets/4060313/0abce1b4-08ec-4d4d-aba9-84607b67b1f4)

**Comment by JPustkuchen** [comment]
Might this be caused by a local settings override? Or did that even happen without custom settings?

**Comment by joshsedl** [comment]
This is indeed a bit weird, @thomasfrobieter always make sure, to have all the recommended VSCode extensions enabled through typing in `@recommended` in `Extensions` tab. We currently have no way to force extension installations.

The only problem I ran into, was that there are multiple formatter provided, so I am going to set a default for css and scss files.
