### ISSUE TITLE
Add "ddev drupal" command

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal-template#151]
I just needed to run `ddev drupal generate:ajax:command` and saw `ddev drupal` is not available.

We should add that shortcut. It simply calls the ./drupal or `./drupal.sh` at `web/core/scripts/`

**Comment by JPustkuchen** [comment]
So won't make sense to add this. I'll leave this open for @joshsedl to look into the core/scripts directory for possible other commands we might want to provide eventually (as separate tasks then).

**Comment by JPustkuchen** [comment]
For my requirement I opened https://github.com/drush-ops/drush/issues/5834

**Comment by JPustkuchen** [comment]
Just found out that ./drupal is something different than ./drupal.sh - so it might still make sense to add that command then!

**Comment by joshsedl** [comment]
Yes, I will add a shortcut!
FYI, I don't think any of the other scripts make sense here! But I'll definitly add a shortcut for `drupal`

**Comment by joshsedl** [comment]
Are you really sure you meant `ddev drupal generate:ajax:command` this sounds like a `ddev drush` command rather than `ddev drupal`? Also googling it, I couldn't find this command.

This is the output, when running the `drupal` php script:
![image](https://github.com/webksde/ddev-vscode-devcontainer-drupal-template/assets/37101709/d62ebd05-5d58-4d67-8312-131fc14260ec)

Doesn't look much of use.

**Comment by JPustkuchen** [comment]
@joshsedl see https://github.com/webksde/ddev-vscode-devcontainer-drupal-template/issues/151#issuecomment-1847509437
and https://github.com/webksde/ddev-vscode-devcontainer-drupal-template/issues/151#issuecomment-1847519615


But there's a theoretical use-case: Generating a new theme from the kit:
https://www.drupal.org/docs/develop/theming-drupal/creating-sub-themes

So if it's just a shortcut, add `ddev drupal` to run the command you screenshoted. If not, just close this. And please finally take a look if there are any other relevant .sh files in that folder that we should add as shortcut. Maybe not.

**Comment by joshsedl** [comment]
Please see https://github.com/webksde/ddev-vscode-devcontainer-drupal-template/issues/151#issuecomment-1847519615 🌝 
drupal.sh != drupal

And we can simply generate a theme using `drush gen`, seems like the script isn't of much need. Gonna close this.
And yea, no other relevant .sh files unfortunately.
