### ISSUE TITLE
Add a command to reset the database to initial state (drowl-reset-db)

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal-template#153]
When developing in ddev, it happens quite frequently that you wish to reset the database to initial state.
This is already possible using `dump-db` or `export-db` if you remember to do this when you set up the project.

Typical cases are for example:
- Test config changes
- Large changes in (fresh) Module development that conflict with the installed module
- ...

But if you don't, your best chance is to set up a fresh DDEV project, which simply costs too much time.
The command should be low-level because in such cases you otherwise run into PHP errors, if Drupal needs to be bootstrapped. For that reason BAM for example can't be accessed typically.

Of course, this requirement is very specific to _Drupal_ development, but that's what the project is for.

**Comment by JPustkuchen** [comment]
@joshsedl if this is a quick-win I think we should add this soon? :)

**Comment by joshsedl** [comment]
Definitely! On it now.

**Comment by joshsedl** [comment]
Fixed!
