### ISSUE TITLE
drowl-init broken with ddev v1.22.6?

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal-template#154]
I just tried setting up a new ddev Drupal 10 project, but ran into these issues:

> Failed to create project: '/home/xyz/ddev/drupal10/.gitignore' is not allowed to be present. composer create needs to be run on a clean/empty project with only the following paths: [web web/sites web/sites/default web/sites/default/.gitignore web/sites/default/settings.ddev.php web/sites/default/settings.php] - please clean up the project before using 'ddev composer create'
> Failed to run drowl-init.sh ; error=exit status 1

I then tried removing the .gitignore (which is simply from this project _(so we might need to add a cleanup step first to drowl-init which removes these irrelevant assets)_ 

But even without these files I then got

> Executing Composer command: [composer create-project --stability RC drupal/recommended-project:^10 --no-install /tmp/jmUcbV]
> In Platform.php line 49:                                                     
>   Could not determine the current working directory  

when running drowl-init.

@joshsedl can you reproduce this using the latest ddev version?

Reproduction: Run
`git clone git@github.com:webksde/ddev-vscode-devcontainer-drupal-template.git ddev-vscode-drupal && cd ddev-vscode-drupal && ddev drowl-init`

as documented.

**Comment by joshsedl** [comment]
Fixed! We just needed to clean up the repo BEFORE running the setup script 👍
