### ISSUE TITLE
[Discussion] Identify potentially helpful Drupal development modules (by needs)

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal-template#3]
Look for useful development modules to speed up development, better code quality, ...

Starting point: 
'browser_refresh',
      'devel',
      'hacked',
      'kint',
      'stage_file_proxy',
...

**Comment by joshsedl** [comment]
Our current drupal module and vscode extension list got quite big in the last couple of month, but there are definitely even more modules / extensions which would speed up development! Let's discuss here, what we could add!

**Comment by joshsedl** [comment]
Most of these modules are enabled. I don't think, this is worthy an issue, but more of an "ongoing process". Hence, I will close this issue.

**Comment by JPustkuchen** [comment]
Well that's nothing special for such a small project mainly used by 3 people (us) 😛 
Let's keep this open as reminder please.

**Comment by joshsedl** [comment]
ok !
